<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CUE4Parse" Version="1.2.2.202607" />
    <PackageReference Include="CUE4Parse-Conversion" Version="1.2.2.202607" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="native\*.dll">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <TargetPath>native\%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
</Project>
